// Country name to flag emoji mapping
export const getCountryFlag = (country) => {
    const flagMap = {
        'Lebanon': '🇱🇧',
        'United States': '🇺🇸',
        'USA': '🇺🇸',
        'United Kingdom': '🇬🇧',
        'UK': '🇬🇧',
        'France': '🇫🇷',
        'Germany': '🇩🇪',
        'Spain': '🇪🇸',
        'Italy': '🇮🇹',
        'Canada': '🇨🇦',
        'Australia': '🇦🇺',
        'Japan': '🇯🇵',
        'China': '🇨🇳',
        'India': '🇮🇳',
        'Brazil': '🇧🇷',
        'Mexico': '🇲🇽',
        'Russia': '🇷🇺',
        'South Korea': '🇰🇷',
        'Netherlands': '🇳🇱',
        'Sweden': '🇸🇪',
        'Norway': '🇳🇴',
        'Denmark': '🇩🇰',
        'Finland': '🇫🇮',
        'Switzerland': '🇨🇭',
        'Belgium': '🇧🇪',
        'Austria': '🇦🇹',
        'Poland': '🇵🇱',
        'Turkey': '🇹🇷',
        'Saudi Arabia': '🇸🇦',
        'UAE': '🇦🇪',
        'Egypt': '🇪🇬',
        'South Africa': '🇿🇦',
        'Argentina': '🇦🇷',
        'Chile': '🇨🇱',
        'Colombia': '🇨🇴',
        'Peru': '🇵🇪',
        'Venezuela': '🇻🇪',
        'Portugal': '🇵🇹',
        'Greece': '🇬🇷',
        'Czech Republic': '🇨🇿',
        'Hungary': '🇭🇺',
        'Romania': '🇷🇴',
        'Ukraine': '🇺🇦',
        'Thailand': '🇹🇭',
        'Vietnam': '🇻🇳',
        'Philippines': '🇵🇭',
        'Indonesia': '🇮🇩',
        'Malaysia': '🇲🇾',
        'Singapore': '🇸🇬',
        'New Zealand': '🇳🇿',
        'Ireland': '🇮🇪',
        'Israel': '🇮🇱',
        'Jordan': '🇯🇴',
        'Morocco': '🇲🇦',
        'Tunisia': '🇹🇳',
        'Algeria': '🇩🇿',
        'Kenya': '🇰🇪',
        'Nigeria': '🇳🇬',
        'Ghana': '🇬🇭',
        'Pakistan': '🇵🇰',
        'Bangladesh': '🇧🇩',
        'Sri Lanka': '🇱🇰',
        'Nepal': '🇳🇵'
    };

    return flagMap[country] || '🌍'; // Default to globe if country not found
};
